### ISSUE TITLE
Error when formatting pytest --log-format argument

### ISSUE THREAD

**Issue by wwuck** [tox-dev/tox-ini-fmt#65]
Running tox-ini-fmt 0.5.0 on the following tox.ini file gives an error:

```ini
[testenv:pytest]
commands = pytest \
           --numprocesses=auto \
           --open-files \
           --cov=my_project \
           --cov-report=xml \
           --junitxml=junit-{envname}.xml \
           --log-format='%(asctime)s %(levelname)s %(message)s' \
           --log-date-format='%Y-%m-%d %H:%M:%S' \
           --log-cli-level='INFO' \
           {posargs}
# Install testenv requirements
deps = pytest
       pytest-antilru
       pytest-cov
       pytest-openfiles
       pytest-randomly
       pytest-xdist[psutil]
```

```
$ tox-ini-fmt tox.ini
Traceback (most recent call last):
  File "/home/devuan/.pyenv/versions/venv/bin/tox-ini-fmt", line 8, in <module>
    sys.exit(run())
  File "/home/devuan/.pyenv/versions/3.9.5/envs/venv/lib/python3.9/site-packages/tox_ini_fmt/__main__.py", line 26, in run
    formatted = format_tox_ini(opts.tox_ini, opts)
  File "/home/devuan/.pyenv/versions/3.9.5/envs/venv/lib/python3.9/site-packages/tox_ini_fmt/formatter/__init__.py", line 22, in format_tox_ini
    order_sections(parser, opts.pin_toxenvs)
  File "/home/devuan/.pyenv/versions/3.9.5/envs/venv/lib/python3.9/site-packages/tox_ini_fmt/formatter/section_order.py", line 20, in order_sections
    sections[section] = dict(parser[section])
  File "/home/devuan/.pyenv/versions/3.9.5/lib/python3.9/configparser.py", line 1255, in __getitem__
    return self._parser.get(self._name, key)
  File "/home/devuan/.pyenv/versions/3.9.5/lib/python3.9/configparser.py", line 799, in get
    return self._interpolation.before_get(self, section, option, value,
  File "/home/devuan/.pyenv/versions/3.9.5/lib/python3.9/configparser.py", line 395, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/home/devuan/.pyenv/versions/3.9.5/lib/python3.9/configparser.py", line 434, in _interpolate_some
    raise InterpolationMissingOptionError(
configparser.InterpolationMissingOptionError: Bad value substitution: option 'commands' in section 'testenv:pytest' contains an interpolation key 'asctime' which is not a valid option name. Raw value: "pytest \\\n--numprocesses=auto \\\n--open-files \\\n--cov=my_project \\\n--cov-report=xml \\\n--junitxml=junit-{envname}.xml \\\n--log-format='%(asctime)s %(levelname)s %(message)s' \\\n--log-date-format='%Y-%m-%d %H:%M:%S' \\\n--log-cli-level='INFO' \\\n{posargs}"
```

**Comment by gaborbernat** [comment]
A PR to fix this would be welcomed 👍
